modLoader="javafml"
loaderVersion="[38,)"
license="Jacky's Minecraft Mods License"

[[mods]]
modId="noautojump"
version="1.18.2-1.0"
displayName="No Auto Jump"
displayURL="https://github.com/JackyyTV/NoAutoJump"
authors="Jackyy"
description='''
Simply forces Auto-Jump to be disabled!
'''

[[dependencies.noautojump]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.noautojump]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="CLIENT"
