modLoader="javafml"
loaderVersion="[44,)"
license="Jacky's Minecraft Mods License"

[[mods]]
modId="noautojump"
version="1.19.4-1.0"
displayName="No Auto Jump"
displayURL="https://github.com/JackyyTV/NoAutoJump"
authors="Jackyy"
description='''
Simply forces Auto-Jump to be disabled!
'''

[[dependencies.noautojump]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.noautojump]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="CLIENT"
