modLoader="javafml"
loaderVersion="[41,)"
license="Jacky's Minecraft Mods License"

[[mods]]
modId="noautojump"
version="1.19.2-1.0"
displayName="No Auto Jump"
displayURL="https://github.com/JackyyTV/NoAutoJump"
authors="Jackyy"
description='''
Simply forces Auto-Jump to be disabled!
'''

[[dependencies.noautojump]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.noautojump]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.19.2)"
    ordering="NONE"
    side="CLIENT"
