modLoader="javafml"
loaderVersion="[35,)"
license="Jacky's Minecraft Mods License"

[[mods]]
modId="noautojump"
version="1.16.5-1.0"
displayName="No Auto Jump"
displayURL="https://github.com/JackyyTV/NoAutoJump"
authors="Jackyy"
description='''
Simply forces Auto-Jump to be disabled!
'''

[[dependencies.noautojump]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.noautojump]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="CLIENT"
